### ISSUE TITLE
🐛 [BUG] - Docker image doesn't run on arm64 systems

### ISSUE THREAD

**Issue by gouthamve** [undb-io/undb#2210]
### Description

The `tini` binary that is pulled in is an `amd64` binary: https://github.com/undb-io/undb/blob/develop/Dockerfile#L28-L31

This fails to run on arm64 servers. It fails with:

```
exec /tini: exec format error
```

Do we even need `tini` here?

### Reproduction steps

```bash
Run undb docker image on any non amd64 architecture.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash

```

**Comment by dontWatchMeCode** [comment]
you can override it in your compose file as a temporary fix

```
services:
  undb:
    ports:
      - 127.0.0.1:3015:3721
    volumes:
      - data:/usr/src/app/.undb
    container_name: undb
    image: ghcr.io/undb-io/undb:latest
    entrypoint: ./undb
``` 

> https://docs.docker.com/get-started/docker-concepts/running-containers/overriding-container-defaults/#override-the-default-cmd-and-entrypoint-in-docker-compose
